[package]
name = "simeioseis"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Thrasos Charalambous"]
license = "MIT"
description = "Academic notes template for Typst"

[template]
path = "template"
entrypoint = "main.typ"